### ISSUE TITLE
Using with URP?

### ISSUE THREAD

**Issue by Cdddo** [sergiobd/TiltbrushHDRP#1]
Do these work with URP? I'm guessing there might be some minor reworking necessary, but I don't know anything about shaders or shader graph... It would be great to have URP versions of these!

**Comment by sergiobd** [comment]
I have not tried them on URP. According to [the manual page](https://docs.unity3d.com/Packages/com.unity.shadergraph@7.1/manual/index.html), shader graph builds shaders that are supported in both HDRP and URP, so most probably it works without reworking. Please try it out!

**Comment by Cdddo** [comment]
I tried and adding them to a URP project made them break because the HDRP master node is not available.

But I rewired them with a URP standard shader master node and they seem to work... I'll clean them up and put them somewhere here soon.

**Comment by sergiobd** [comment]
Great!

**Comment by trainman1974** [comment]
@Cdddo hello, I'm making a gallery for a mobile app using TiltBrush, if you could share a version of the shaders for URP, I'd be very happy.
